### ISSUE TITLE
Cannot scroll down when using swipe left/right

### ISSUE THREAD

**Issue by markelarizaga** [RyanMullins/angular-hammer#16]
Hi, I am trying to use the left/right swipe and it is working properly. The problem is that if I use them the element does not scroll down anymore as it did by default.
What I want is to perform certain actions when swiping left/right but still let the element scroll down when making the down-to-top gesture. I thought this could be achieved by calling event.preventDefault() but it is not the case.

Am I forgeting anything here?
Thanks in advance.

**Comment by RyanMullins** [comment]
I am thinking this may be due to recognizers not being instantiated with a direction in my code. Reopening until I verify/fix this.
