### ISSUE TITLE
Angular-hammer throws TypeError when evaluating angular expressions

### ISSUE THREAD

**Issue by ramoneguru** [RyanMullins/angular-hammer#28]
Fiddle here: http://jsfiddle.net/ramoneguru/b1sckc80/

I was using the hm-tap feature to evaluate the following:
```
<h1 ng-init="test1 = true" hm-tap="test1 = !test1">Click here to see value: {{test1}}</h1>
```

When toggling the test1 value I get an error in the console, "TypeError: undefined is not a function"
Updating test1's value from "false" to "true": "TypeError: undefined is not a function"
Updating test1's value from "true" to "false": No error

Error seems to happen on line 168 of angular.hammer.js
```
if (fn) {
  fn.call(scope, event);
}
```

**Comment by RyanMullins** [comment]
Fixed in #29
