### ISSUE TITLE
hm-swiperight stops me from scrolling...

### ISSUE THREAD

**Issue by quadrupleslap** [RyanMullins/angular-hammer#34]
I don't know if this is intended behaviour or not, but when I use the hm-swipeleft or hm-swiperight directive on an li, I can't scroll the list by dragging that li normally.

**Comment by quadrupleslap** [comment]
Although I suspect preventDefault in the options might fix that. =)

**Comment by mattmcdonald-uk** [comment]
Do you have an example for this issue?

**Comment by quadrupleslap** [comment]
```js
<ul class="entries">

  <li ng-repeat="entry in entries | reverse | orderBy: '!!complete'"
      ng-class="{complete: entry.complete}" class="entry"

      hm-recognizer-options='{"type":"swiperight", "threshold":10, "preventDefault":false}'
      hm-swiperight="editEntry(entry, {complete: !entry.complete})"

      animated-reorder>
    <button class="glyphicon glyphicon-ok" ng-click="editEntry(entry, {complete: !entry.complete})" ink-ripple></button>
    <p ng-bind="entry.title || entry.input"></p>
  </li>

</ul>
```

**Comment by mattmcdonald-uk** [comment]
I can't reproduce this.

Created a similar structure to yours (without specifying preventDefault) and the ul scrolls fine and the swiperight event is also firing fine.

If you're sure it's a library bug, can you provide a plunker or similar with a runnable/reproducible error.

**Comment by quadrupleslap** [comment]
Whoops, sorry, it's my fault. I was doing something really stupid with overflow-scrolling.
