### ISSUE TITLE
Doesn't Install Dependencies Automatically When Used with Browserify

### ISSUE THREAD

**Issue by trisys3** [RyanMullins/angular-hammer#48]
When I use this module with browserify, it works great except that it doesn't install angular or hammerjs by itself, so I have to manually go in and install them with `(cd node_modules/angular-hammer && npm i angular hammer)`. This seems like a simple fix: just put them into a `dependencies` field in the `package.json`. Any reason why this has not been done yet?

Besides this minor quibble, great job with the directives! It's been working great with browserify, even without browserify-shim.

**Comment by RyanMullins** [comment]
This should be fixed with changes in #55. Take a look and update accordingly.

**Comment by trisys3** [comment]
Thanks, I'll look at it when I get to work.

**Comment by trisys3** [comment]
Is there a way to install version 2.2-jsdw, as that seems to be the current version? I apologize, I have never needed to install anything but vanilla semver versions. Also, we will probably not be able to use this in production yet.

**Comment by RyanMullins** [comment]
I would say the easiest way is to manually install it by copying files around. You can use direct references to Git repos with Bower, but I don't think NPM supports them.

**Comment by trisys3** [comment]
OK, I will try to test that at some point, but as I said I will not use it in production just yet.

**Comment by trisys3** [comment]
Looks like that works. I would need to have the `hammer.js` file accessible to the `browserify` module, or else have it as a `browserify` external, but I can figure that out. Thanks!
